name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest dvc matplotlib seaborn pandas numpy

    # Step 4: Run tests
    - name: Run tests
      run: |
        pytest || echo "No tests found, skipping"

    # Step 5: Run Python scripts (optional)
    - name: Run main scripts
      run: |
        if [ -f main.py ]; then python main.py; fi

    # Step 6: Generate DVC plots (if using DVC)
    - name: Generate DVC plots
      run: |
        if [ -f dvc.yaml ]; then
          dvc pull
          dvc plots show --all || echo "No DVC plots found"
        fi
